# Generated by Django 4.1.7 on 2023-05-30 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Турция', 'ТУРЦИЯ'), ('Оаэ', 'ОАЭ'), ('Египет', 'ЕГИПЕТ'), ('Греция', 'ГРЕЦИЯ')], default='Турция', max_length=32),
        ),
    ]
