# Generated by Django 4.1.7 on 2023-05-31 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_remove_product_color_product_country_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('country', models.CharField(choices=[('Турция', 'ТУРЦИЯ'), ('Оаэ', 'ОАЭ'), ('Египет', 'ЕГИПЕТ'), ('Греция', 'ГРЕЦИЯ')], default='Турция', max_length=32)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]

