# Generated by Django 4.1.7 on 2023-06-18 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0010_purchase_delete_onehotel_remove_product_color_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Purchase",
            new_name="Booking",
        ),
    ]
